version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Abc@123099
  web:
    build: .
    restart: always
    command: python manage.py
    volumes:
      - .:/usr/src/flask
    ports:
      - "8080:8080"
    depends_on:
      - db